name: Publish to pub.dev

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dart-lang/setup-dart@v1
      with:
        channel: stable
    - uses: dart-lang/setup-pub@v1
    - run: pub get
    - run: pub run test
    - run: pub run build_runner build --delete-conflicting-outputs
    - run: dart format --set-exit-if-changed .
    - run: dart analyze
  publish:
    permissions:
      id-token: write
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1